# Generated by Django 5.2.4 on 2025-09-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requester_name', models.CharField(max_length=100)),
                ('requester_type', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('units_needed', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=5, unique=True)),
                ('units_available', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('health_status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('units_donated', models.IntegerField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donors')),
            ],
        ),
        migrations.AddField(
            model_name='donors',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.users'),
        ),
    ]
